# -*- mode: python ; coding: utf-8 -*-

import pyfiglet
from PyInstaller.utils.hooks import collect_data_files

a = Analysis(
    ['Main.py'],
    pathex=[],
    binaries=[],
    datas=collect_data_files('pyfiglet'),  # Включаем шрифты pyfiglet
    hiddenimports=[
        'adb_shell', 'aiohttp', 'aiosignal', 'altgraph', 'annotated_types',
        'anyio', 'Appium_Python_Client', 'arrow', 'attrs', 'backoff', 'bcrypt',
        'beautifulsoup4', 'beeware', 'bidict', 'binaryornot', 'blinker', 
        'branca', 'briefcase', 'Brotli', 'build', 'buildozer', 'cachetools',
        'certifi', 'cffi', 'chardet', 'charset_normalizer', 'click', 
        'click_plugins', 'clr_loader', 'colorama', 'comtypes', 'contourpy', 
        'cookiecutter', 'cryptography', 'customtkinter', 'cv', 'cycler', 
        'Cython', 'darkdetect', 'decorator', 'distlib', 'distro', 'dnspython',
        'docutils', 'email_validator', 'fastapi', 'fastui', 'ffpyplayer', 
        'filelock', 'Flask', 'Flask_SocketIO', 'Flask_SQLAlchemy', 
        'Flask_WTF', 'folium', 'fonttools', 'frozenlist', 'future', 'geocoder',
        'geographiclib', 'geopy', 'git_filter_repo', 'gitdb', 'GitPython',
        'greenlet', 'h11', 'httpcore', 'httpx', 'idna', 'imageio', 
        'imageio_ffmpeg', 'iniconfig', 'ipinfo', 'itsdangerous', 'Jinja2', 
        'joblib', 'keyboard', 'Kivy', 'kivy_deps_angle', 'kivy_deps_glew', 
        'kivy_deps_sdl2', 'Kivy_Garden', 'kiwisolver', 'lxml', 'markdown_it_py', 
        'MarkupSafe', 'matplotlib', 'mdurl', 'MouseInfo', 'moviepy', 'mss',
        'multidict', 'mutagen', 'numpy', 'openai', 'opencage', 'opencv_python', 
        'outcome', 'packaging', 'pafy', 'pandas', 'paramiko', 'pefile', 
        'pexpect', 'phonenumbers', 'pillow', 'platformdirs', 'playwright',
        'pluggy', 'ply', 'proglog', 'psutil', 'ptyprocess', 'pyasn1', 
        'PyAutoGUI', 'pycparser', 'pycryptodomex', 'pydantic', 'pydantic_core',
        'pydub', 'pyee', 'pyfiglet', 'pygame', 'PyGetWindow', 'Pygments',
        'pyinstaller', 'pyinstaller_hooks_contrib', 'pylnk', 'PyMsgBox', 
        'PyNaCl', 'pyngrok', 'pyparsing', 'pyperclip', 'pypiwin32', 'pypng', 
        'pyproject_hooks', 'PyQt5', 'PyQt5_Qt5', 'PyQt5_sip', 'PyQt6', 
        'PyQt6_Qt6', 'PyQt6_sip', 'PyRect', 'PyScreeze', 'PySide6', 
        'PySide6_Addons', 'PySide6_Essentials', 'PySocks', 'pytest', 
        'python_dateutil', 'python_dotenv', 'python_engineio', 'python_nmap', 
        'python_slugify', 'python_socketio', 'python_vlc', 'pythonnet', 'pytube', 'scapy',
        'pytweening', 'pytz', 'pywifi', 'pywin32', 'pywin32_ctypes', 'PyYAML', 
        'qrcode', 'ratelim', 'regex', 'requests', 'requests_file', 'rich', 'rsa', 
        'scapy', 'scikit_learn', 'scipy', 'secure_smtplib', 'selenium', 
        'setuptools', 'sh', 'shiboken6', 'shodan', 'simple_websocket', 'sip',
        'six', 'smmap', 'sniffio', 'sortedcontainers', 'sounddevice', 'soupsieve',
        'SQLAlchemy', 'sshtunnel', 'starlette', 'text_unidecode', 
        'threadpoolctl', 'TikTokApi', 'tkintermapview', 'tldextract', 'toga', 
        'toga_core', 'toga_winforms', 'toml', 'tomli_w', 'tqdm', 'travertino', 
        'trio', 'trio_websocket', 'ttkbootstrap', 'types_python_dateutil', 
        'typing_extensions', 'tzdata', 'urllib3', 'virtualenv', 'webdriver_manager',
        'websockets', 'Werkzeug', 'wfastcgi', 'wheel', 'winshell', 'wsproto', 
        'WTForms', 'XlsxWriter', 'xyzservices', 'yarl', 'youtube_dl', 'yt_dlp'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
